// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9zZxh2_fasp9PMV1uC6JBtj4zl8IKCok',
    appId: '1:543857228034:web:00f7b6520258e7014d2a1b',
    messagingSenderId: '543857228034',
    projectId: 'fir-analyticsflutter-1209c',
    authDomain: 'fir-analyticsflutter-1209c.firebaseapp.com',
    storageBucket: 'fir-analyticsflutter-1209c.appspot.com',
    measurementId: 'G-WQZDGB4NGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG1uGMUlPVBG6Fg49M4knBwbZcqd9wIu4',
    appId: '1:543857228034:android:57d281208a7e13dd4d2a1b',
    messagingSenderId: '543857228034',
    projectId: 'fir-analyticsflutter-1209c',
    storageBucket: 'fir-analyticsflutter-1209c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMBLziy6Ncm729F6XdCquQzQ3SAlJ0GHc',
    appId: '1:543857228034:ios:7a9b5952e3cda3b94d2a1b',
    messagingSenderId: '543857228034',
    projectId: 'fir-analyticsflutter-1209c',
    storageBucket: 'fir-analyticsflutter-1209c.appspot.com',
    iosBundleId: 'com.example.firebaseAnalytics2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMBLziy6Ncm729F6XdCquQzQ3SAlJ0GHc',
    appId: '1:543857228034:ios:7a9b5952e3cda3b94d2a1b',
    messagingSenderId: '543857228034',
    projectId: 'fir-analyticsflutter-1209c',
    storageBucket: 'fir-analyticsflutter-1209c.appspot.com',
    iosBundleId: 'com.example.firebaseAnalytics2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9zZxh2_fasp9PMV1uC6JBtj4zl8IKCok',
    appId: '1:543857228034:web:3f97d0f031861dfb4d2a1b',
    messagingSenderId: '543857228034',
    projectId: 'fir-analyticsflutter-1209c',
    authDomain: 'fir-analyticsflutter-1209c.firebaseapp.com',
    storageBucket: 'fir-analyticsflutter-1209c.appspot.com',
    measurementId: 'G-WYLSRYXW2Q',
  );
}
